# -*- coding: utf-8 -*-
{
'contest_id'             : '2270488',
'cookie'                 : 'ACSID=AJKiYcHAIbX2Z8F78JY_hZQ9TBD4hlr7fSJckFjT4TVTRmgEXy-1fxolq6-TEq00oItG1_1IGHV5rv35K1iH5yWyaXMZRBogVBaFm5Ty0x-Ac5fRss8SVMIZbi7h4L9je6HSTIsMbewDWpW_TxxxEiVIrq9OzX1q2Gsppa-liygL2118tSXbhkYhHuy_Hm0czrSRYDmJCgYw4s6iBgpYd-NxyCHZtBp2jwF4ysJv6DdcvnlAOw277f96U8Pzkwi8xvatCYaGaf3398QNKBocKPtm5HrqVhBQcQXfZ9OGuSk0eNPhoZ4kyoWVFcDiAF5w7Epb7ZAMkia9H78-H3dolVfCa6J8FS4Zkqa0-QxfcZpZb14R1IpXDnBE8Ca_jJ9QTQYFIUwnRUu9-RMVsggcMiFZUj-4qpZn5_9Kfbo8QLj7ZODGgjZDyrIm4-2dDpiZw3QDlVe8Wtj2VsjgDxqdvIpBY3jhr0_15IEFhGjpFlKGktj6H5dylZxw2cYWIQxuCuIvsDPU9mz01totVxaMcNQJd0yftgpr8tdji6MFBvVPmkJCJT6L4xUjygtwWUJaMbApqs_yZmBnqQEueeutKjq9judtkIKclw; expires=Mon, 03-Mar-2014 20:04:00 GMT; path=/',
'data_directory'         : './source',
'host'                   : 'code.google.com',
'input_name_format'      : '{problem}-{input}-{id}.in',
'middleware_tokens'      : {u'SubmitAnswer': u'Njc5MzBlZWIzYjU3MzY1ZTY2NzcxMGQ2MjExNzg0MWV8MTA1MjQ5MjkwNTY0OTg0MDM4Njc4fDEzOTM3OTA2NDEyMjI4ODA=', u'GetInitialValues': u'Njc5MzBlZWIzYjU3MzY1ZTY2NzcxMGQ2MjExNzg0MWV8MTA1MjQ5MjkwNTY0OTg0MDM4Njc4fDEzOTM3OTA2NDEyMjI4ODA=', u'GetUserStatus': u'Njc5MzBlZWIzYjU3MzY1ZTY2NzcxMGQ2MjExNzg0MWV8MTA1MjQ5MjkwNTY0OTg0MDM4Njc4fDEzOTM3OTA2NDEyMjI4ODA=', u'GetInputFile': u'Njc5MzBlZWIzYjU3MzY1ZTY2NzcxMGQ2MjExNzg0MWV8MTA1MjQ5MjkwNTY0OTg0MDM4Njc4fDEzOTM3OTA2NDEyMjI4ODA='},
'output_name_format'     : '{problem}-{input}-{id}.out',
'problems'               : [{'io_set_name_to_index': {u'small': 0, u'large': 1}, 'io_sets': [{'time_limit': 240, 'name': u'small', 'global_index': 0, 'difficulty': 0, 'points': 10, 'difficulty_name': 'small', 'input_id': 0, 'public': True}, {'time_limit': 480, 'name': u'large', 'global_index': 1, 'difficulty': 1, 'points': 20, 'difficulty_name': 'large', 'input_id': 1, 'public': False}], 'id': 2453486, 'key': u'agpzfmdjai1wcm9kchELEghwcm9ibGVtcxju35UBDA', 'name': u'Tic-Tac-Toe-Tomek'}, {'io_set_name_to_index': {u'small': 0, u'large': 1}, 'io_sets': [{'time_limit': 240, 'name': u'small', 'global_index': 2, 'difficulty': 0, 'points': 10, 'difficulty_name': 'small', 'input_id': 0, 'public': True}, {'time_limit': 480, 'name': u'large', 'global_index': 3, 'difficulty': 1, 'points': 30, 'difficulty_name': 'large', 'input_id': 1, 'public': False}], 'id': 2449486, 'key': u'agpzfmdjai1wcm9kchELEghwcm9ibGVtcxjOwJUBDA', 'name': u'Lawnmower'}, {'io_set_name_to_index': {u'small': 0, u'large1': 1, u'large2': 2}, 'io_sets': [{'time_limit': 240, 'name': u'small', 'global_index': 4, 'difficulty': 0, 'points': 10, 'difficulty_name': 'small', 'input_id': 0, 'public': True}, {'time_limit': 480, 'name': u'large1', 'global_index': 5, 'difficulty': 1, 'points': 35, 'difficulty_name': 'large', 'input_id': 1, 'public': False}, {'time_limit': 480, 'name': u'large2', 'global_index': 6, 'difficulty': 1, 'points': 55, 'difficulty_name': 'large', 'input_id': 2, 'public': False}], 'id': 2463486, 'key': u'agpzfmdjai1wcm9kchELEghwcm9ibGVtcxj-rZYBDA', 'name': u'Fair and Square'}, {'io_set_name_to_index': {u'small': 0, u'large': 1}, 'io_sets': [{'time_limit': 240, 'name': u'small', 'global_index': 7, 'difficulty': 0, 'points': 20, 'difficulty_name': 'small', 'input_id': 0, 'public': True}, {'time_limit': 480, 'name': u'large', 'global_index': 8, 'difficulty': 1, 'points': 60, 'difficulty_name': 'large', 'input_id': 1, 'public': False}], 'id': 2458486, 'key': u'agpzfmdjai1wcm9kchELEghwcm9ibGVtcxj2hpYBDA', 'name': u'Treasure'}],
'source_names_format'    : ['{problem}--{input}--{id}.cpp'],
'tokens_expiration_time' : u'2014-03-04 20:04:01',
'user'                   : 'jiefeng.hopkins@gmail.com',
}
