#!/usr/bin/env perl 
#===============================================================================
#
#         FILE: ex15-2.pl
#
#        USAGE: ./ex15-2.pl  
#
#  DESCRIPTION: 
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: Jie Feng (http://hey.i-feng.org), jokerfeng2010@gmail.com
# ORGANIZATION: 
#      VERSION: 1.0
#      CREATED: 01/16/2014 03:17:15 AM
#     REVISION: ---
#===============================================================================

#use strict;
use warnings;
use utf8;
use feature qw/state say switch/;

my $num = <STDIN>;
given ($num){
    when ($num%3==0) {print "Fizz";continue } 
    when ($num%5==0) {print "Bin";continue}
    when ($num%7==0) {print "Sausage";continue}
}
